name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create PEM file
      run: echo "${{ secrets.EC2_PEM_KEY }}" > /tmp/your-key.pem

    - name: Set permissions on PEM file
      run: chmod 600 /tmp/your-key.pem

    - name: Test SSH Connection
      run: |
        ssh -i /tmp/your-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PEM_KEY }}
        port: 22
        script: |
          cd /server/ProjetRH
          docker-compose pull
          cd /server/ProjetRH/deployment/aws
          docker-compose down
          docker-compose up -d